### PR TITLE
Fixed bugs, added documentation, added logger, added CI, fixed typos,…

### LINKED ISSUE #1: Add documentation for API
The API needs to be documented and each field in the API needs to be briefly explained so it can be understood by outside readers

https://github.com/dana-team/hns-nodeQuotaSync-plugin/blob/46ca5f5b968b1d8bf34ce7b63d38aac77662b6a1/api/v1alpha1/nodequotaconfig_types.go#L28-L55

/kind documentation

### PR DESCRIPTION
**Pull request by sahar2339**
… bumped Golang to 1.20, made the code more readable and stable overall.

fixed  #1 #2 #3 #4 #5 #8 #7 #6

### CODE REVIEW

File: api/v1alpha1/nodequotaconfig_types.go [hunk 1]
```diff
@@ -26,25 +26,44 @@ import (
 
 // NodeQuotaConfigSpec defines the desired state of NodeQuotaConfig
 type NodeQuotaConfigSpec struct {
-	ReservedHoursTolive int                  `json:"reservedHoursToLive,omitempty"`
-	ControlledResources []string             `json:"controlledResources,omitempty"`
-	Roots               []SubnamespacesRoots `json:"subnamespacesRoots,omitempty"`
+	// ReservedHoursTolive defines how many hours the reservedresources can live until they removed from the cluster resources
+	ReservedHoursTolive int `json:"reservedHoursToLive"`
```
Comment (mzeevi) [inline api/v1alpha1/nodequotaconfig_types.go:30]: // ReservedHoursToLive defines how many hours the ReservedResources can live until they are removed from the cluster resources

Also rename `ReservedHoursTolive` to `ReservedHoursToLive`

File: api/v1alpha1/nodequotaconfig_types.go [hunk 2]
```diff
@@ -26,25 +26,44 @@ import (
...
+
+	// ControlledResources defines which resources the controller will calculate from the nodes
+	// Possible values exmpales: ["cpu","memory"], ["cpu","gpu"]
+	ControlledResources []string `json:"controlledResources"`
```
Comment (mzeevi) [inline api/v1alpha1/nodequotaconfig_types.go:34]: // ControlledResources defines which node resources are controlled
// Possible values examples: ["cpu","memory"], ["cpu","gpu"]

File: api/v1alpha1/nodequotaconfig_types.go [hunk 3]
```diff
@@ -26,36 +26,36 @@ import (
...
 type SubnamespacesRoots struct {
 	// RootNamespace is the name of the root namespace
 	RootNamespace string `json:"rootNamespace"`
-	// SecondaryRoots are the subnamespaces that under the root namespace
+	// SecondaryRoots are the subnamespaces under the root namespace
 	SecondaryRoots []NodeGroup `json:"secondaryRoots"`
 }
 
-// NodeGroup defines a group of nodes thats allocated to the secondray root workloads
+// NodeGroup defines a group of nodes that allocated to the secondary root workloads
```
Comment (mzeevi) [inline api/v1alpha1/nodequotaconfig_types.go:58]: //... that are allocated*

File: README.md [hunk 4]
```diff
@@ -1,7 +1,7 @@
 
 # NodeQuotaSync Plugin for HNS
 
-The NodeQuotaSync plugin enables syncing the root subnamespace and secondary subnamespace with the nodes allocatable resources in the cluster. It provides support for resources multiplier for over commit and reserved resources mechanism, making it easier to troubleshoot nodes without affecting the subnamespace wallets.
+The NodeQuotaSync plugin enables syncing the root subnamespace and secondary subnamespace with the nodes allocatable resources in the cluster. It provides support for resources multiplier for over commit and reserved resources mechanism, making it easier to remove nodes from the cluster temporarily without affecting the subnamespace wallets.
```
Comment (mzeevi) [inline README.md]: secondary subnamespaces* no?

File: internal/utils/nodeGroup.go [hunk 5]
```diff
@@ -23,90 +29,144 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
+		NodeGroup: nodeGroupName,
+		Resources: debt,
+		Timestamp: metav1.Now(),
+	})
+	logr.Info(fmt.Sprintf("Added ReservedResources to nodeGroup %s", nodeGroupName))
+}
+
+// removeReservedfromConfig removes the reserved resources for a node group from the NodeQuotaConfig.
+// It takes the node group name and the NodeQuotaConfig to modify.
+func removeReservedfromConfig(nodeGroupName string, config *danav1alpha1.NodeQuotaConfig) {
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go:126]: removeReservedFromConfig*

File: internal/controllers/nodequotaconfig_controller.go [hunk 6]
```diff
@@ -68,47 +72,64 @@ func (r *NodeQuotaConfigReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
 			return err
 		}
 	}
 	return nil
 }
 
-func (r *NodeQuotaConfigReconciler) requestConfigReconcile(node client.Object) []reconcile.Request {
+// requestConfigReconcile generates a list of reconcile requests for NodeQuotaConfig objects that need to be reconciled based on the given node.
+// It takes a context and the node object.
+// It returns a slice of reconcile requests ([]reconcile.Request).
```
Comment (mzeevi) [inline internal/controllers/nodequotaconfig_controller.go:129]: `based on the given node` is a bit misleading, no?

File: internal/utils/nodeGroup.go [hunk 7]
```diff
@@ -23,90 +29,144 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
 	}
-	AddReservedToConfig(debt, secondaryRoot.Name, config)
-	sns.Spec.ResourceQuotaSpec.Hard = FillterUncontrolledResources(plus, config.Spec.ControlledResources)
-	if err := r.Update(ctx, &sns); err != nil {
-		return err, v1.ResourceList{}
+	groupReserved := getReservedResourcesByGroup(secondaryRoot.Name, *config)
+	if isGreaterThan(sns.Spec.ResourceQuotaSpec.Hard, groupResources) {
+		// Nodes removed
+		debt := subtractTwoResourceList(sns.Spec.ResourceQuotaSpec.Hard, groupResources)
+		if groupReserved.NodeGroup == "" || hoursPassedSinceDate(groupReserved.Timestamp) < int(config.Spec.ReservedHoursTolive) {
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go]: Put ` hoursPassedSinceDate(groupReserved.Timestamp) < int(config.Spec.ReservedHoursTolive)` in a different function. Also the `int` here is a redundant conversion

File: internal/controllers/nodequotaconfig_controller.go [hunk 8]
```diff
@@ -68,47 +72,64 @@ func (r *NodeQuotaConfigReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
 		if err != nil {
+			logger.Error(err, fmt.Sprintf("Error getting the %s resourceQuota", rootSubnamespace.RootNamespace))
 			return err
 		} else {
-			rootRQ.Spec.Hard = utils.FillterUncontrolledResources(rootResources, config.Spec.ControlledResources)
+			rootRQ.Spec.Hard = rootResources
+			logger.Info(fmt.Sprintf("Updating RootSubnamespace %s with new resources", rootSubnamespace.RootNamespace))
 			if err := r.Update(ctx, &rootRQ); err != nil {
 				return err
 			}
```
Comment (mzeevi) [inline internal/controllers/nodequotaconfig_controller.go:108]: Put the update of the root namespace wallet and the update of the secondary roots in different functions

File: internal/controllers/nodequotaconfig_controller.go [hunk 9]
```diff
@@ -68,47 +72,64 @@ func (r *NodeQuotaConfigReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
-	if !reflect.DeepEqual(oldConfigStatus, config.Status) {
+	utils.DeleteExpiredReservedResources(&config, logger)
+	if !reflect.DeepEqual(oldConfigStatus.ReservedResources, config.Status.ReservedResources) {
 		if err := r.Status().Update(ctx, &config); err != nil {
+			logger.Error(err, fmt.Sprintf("Error updating the NodeQuotaConfig"))
 			return err
 		}
 	}
 	return nil
 }
```
Comment (mzeevi) [inline internal/controllers/nodequotaconfig_controller.go:125]: Put the status update in a different function

File: internal/utils/nodeGroup.go [hunk 10]
```diff
@@ -23,90 +29,144 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
 }
 
-func DeleteExpiredReservedResources(config *danav1alpha1.NodeQuotaConfig) {
+// DeleteExpiredReservedResources removes the expired reserved resources from the NodeQuotaConfig.
+// It takes the NodeQuotaConfig to modify and a logger for logging informational messages.
+func DeleteExpiredReservedResources(config *danav1alpha1.NodeQuotaConfig, logger logr.Logger) {
 	newReservedResources := []danav1alpha1.ReservedResources{}
 	for _, resources := range config.Status.ReservedResources {
-		if HoursPassedSinceDate(resources.Timestamp) < int(config.Spec.ReservedHoursTolive) {
+		if hoursPassedSinceDate(resources.Timestamp) < int(config.Spec.ReservedHoursTolive) {
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go]: This condition is often used and should be a simple function with an indicative name instead

**Comment by mzeevi** [comment]
1. Change the `README.md` please so that the example uses generic names instead of `sahar` and `omer`
2. There are still a few typos here and there, `ContainesRootAnnotation` for example (which seems to be an unused function)
3. Change `annos` to `annotations` (it was also changed in HNS) in the code
4. We should discuss how to e2e testing here, please open an issue for that

File: README.md [hunk 11]
```diff
@@ -36,21 +31,46 @@ spec:
...
         - labelSelector:
-            app: omer
-          name: omer
+            app: cpu-workloads
+          name: cpu-workloads
           multipliers:
             memory: "4"
 ```
 
+subnamespaceRoots defines the cluster's hierarchy, the `name` field represents the name of the `root` namespace and the secondaryRoots are the direct children of the `root` namespaces with thier corresponding node's labelSelector and multipliers.
```
Comment (mzeevi) [inline README.md:49]: their*

File: README.md [hunk 12]
```diff
@@ -36,21 +31,46 @@ spec:
...
+  reservedResources:
+    - Timestamp: '2023-07-09T07:04:27Z'
+      nodeGroup: cpu-workloads
+      resources:
+        cpu: 3500m
+        memory: '61847027712'
+        pods: '250'
+```
+
+The cluster's resources won't update until we either return the node's resources or the number of hours in the `ReservedHoursTolive` will pass from the `Timestamp` and then the resources will be removed.
```
Comment (mzeevi) [inline README.md:67]: ReservedHoursToLive*

File: internal/controllers/nodequotaconfig_controller.go [hunk 13]
```diff
@@ -68,47 +77,56 @@ func (r *NodeQuotaConfigReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
 
-func (r *NodeQuotaConfigReconciler) CalculateRootSubnamespaces(ctx context.Context, config danav1alpha1.NodeQuotaConfig) error {
-	oldConfigStatus := config.Status.DeepCopy()
-	reservedResources := []danav1alpha1.ReservedResources{}
+// CalculateRootSubnamespaces calculates the resource allocation for the root subnamespaces based on the provided NodeQuotaConfig.
+// It takes a context, the NodeQuotaConfig to reconcile, and a logger for logging informational messages.
+// It returns an error (if any occurred) during the calculation.
+func (r *NodeQuotaConfigReconciler) CalculateRootSubnamespaces(ctx context.Context, config danav1alpha1.NodeQuotaConfig, logger logr.Logger) error {
 	for _, rootSubnamespace := range config.Spec.Roots {
+		logger.Info(fmt.Sprintf("Starting to calculate RootSubnamespace %s", rootSubnamespace.RootNamespace))
```
Comment (mzeevi) [inline internal/controllers/nodequotaconfig_controller.go:91]: I think it would be better in terms of readability to move the `for` loop into the main Reconcile code and pass the rootNamespace name as an argument to this function. WDYT?

Also, the root namespace is not a subnamespace (there's no subnamespace CR for it)

File: internal/utils/nodeGroup.go [hunk 14]
```diff
@@ -23,90 +29,178 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
+	if err := client.Update(ctx, &rootRQ); err != nil {
+		logger.Error(err, fmt.Sprintf("Error updating rootSubnamespace %s", rootSubnamespace.RootNamespace))
+		return err
+	}
+	return nil
+}
+
+// UpdateRootSubnamespace updates the secondaryRoots in the cluster with the new quantity of resources.
+// It takes slice of Subnamespaces that was updated in memory and does API requests to commit the update.
+func UpdateProcessedSecondaryRoots(ctx context.Context, processedSecondaryRoots []danav1.Subnamespace, logger logr.Logger, client client.Client) error {
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go:124]: The comment references the wrong function

File: internal/utils/nodeGroup.go [hunk 15]
```diff
@@ -23,90 +29,178 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
 
-func ProcessSecondaryRoot(ctx context.Context, r client.Client, secondaryRoot danav1alpha1.NodeGroup, config *danav1alpha1.NodeQuotaConfig, rootSubnamespace string) (error, v1.ResourceList) {
+// isReservedResourceExpired checks if a reserved created more than X hours ago, defined by the user in the config CRD.
+func isReservedResourceExpired(reservedResources danav1alpha1.ReservedResources, config danav1alpha1.NodeQuotaConfig) bool {
+	return hoursPassedSinceDate(reservedResources.Timestamp) >= config.Spec.ReservedHoursToLive
+}
+
+// setReservedToConfig sets the reserved resources for a node group in the NodeQuotaConfig.
+// It takes the resource debt (v1.ResourceList) to set, the node group name, the NodeQuotaConfig to modify, and a logger for logging informational messages.
+func setReservedToConfig(debt v1.ResourceList, nodeGroupName string, config *danav1alpha1.NodeQuotaConfig, logr logr.Logger) {
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go:142]: Rename `logr` to `logger` to keep it consistent across all `logr.Logger` instances

File: internal/utils/nodeGroup.go [hunk 16]
```diff
@@ -23,90 +29,178 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
+		return
+	}
+	config.Status.ReservedResources = slices.Delete(config.Status.ReservedResources, index, index+1)
+}
+
+// ProcessSecondaryRoot processes a secondary root node group and updates the corresponding Subnamespace object and add reserved resources to the config if needed.
+// It takes a context, a client for making API requests, the secondary root node group, the NodeQuotaConfig,
+// the root subnamespace, and a logger for logging informational messages.
+// It returns an error (if any occurred) and the updated Subnamespace object (danav1.Subnamespace).
+func ProcessSecondaryRoot(ctx context.Context, r client.Client, secondaryRoot danav1alpha1.NodeGroup, config *danav1alpha1.NodeQuotaConfig, rootSubnamespace string, logr logr.Logger) (error, danav1.Subnamespace) {
```
[the remark this answers is not in the document]
Comment (mzeevi) [reply internal/utils/nodeGroup.go:177]: You actually don't need to pass the logger here since you can create it from ctx within the scope of the function

File: internal/utils/nodeGroup.go [hunk 17]
```diff
@@ -15,6 +18,9 @@ import (
 	danav1alpha1 "nodeQuotaSync/api/v1alpha1"
 )
 
+// CalculateNodeGroup calculates the resource list for a node group based on the provided nodes, NodeQuotaConfig, and node group name.
+// It takes a context, a NodeList containing the nodes, the NodeQuotaConfig, and the node group name.
+// It returns the calculated resource list (v1.ResourceList) for the node group.
 func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alpha1.NodeQuotaConfig, nodeGroup string) v1.ResourceList {
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go:24]: ctx is unused

File: internal/utils/nodeGroup.go [hunk 18]
```diff
@@ -15,6 +18,9 @@ import (
...
 	var ResourceMultiplier map[string]string
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go:25]: Would probably be better to move this to a different function with a single responsibility that just returns the ResourceMultiplier

File: internal/utils/nodeGroup.go [hunk 19]
```diff
@@ -23,90 +29,178 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
+		config.Status.ReservedResources = append(config.Status.ReservedResources, reservedResources)
+		return
+	}
+	config.Status.ReservedResources = append(config.Status.ReservedResources, danav1alpha1.ReservedResources{
+		NodeGroup: nodeGroupName,
+		Resources: debt,
+		Timestamp: metav1.Now(),
+	})
+	logr.Info(fmt.Sprintf("Added ReservedResources to nodeGroup %s", nodeGroupName))
+}
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go:156]: Not sure I understand the code here. Can't this function be re-written as something simpler like:

```
func setReservedToConfig(debt v1.ResourceList, nodeGroupName string, config *danav1alpha1.NodeQuotaConfig, logr logr.Logger) {
	if doesReservedResourceExist(*config, nodeGroupName) {
		removeReservedFromConfig(nodeGroupName, config)
	}
	config.Status.ReservedResources = append(config.Status.ReservedResources, danav1alpha1.ReservedResources{
		NodeGroup: nodeGroupName,
		Resources: debt,
		Timestamp: metav1.Now(),
	})
	logr.Info(fmt.Sprintf("Added ReservedResources to nodeGroup %s", nodeGroupName))
}
```

Comment (mzeevi) [reply internal/utils/nodeGroup.go:156]: Also should probably rename the function from `setReservedToConfig` to `addReservedResourcesToConfigStatus` since this is what it actually does

File: internal/utils/resources.go [hunk 20]
```diff
@@ -8,21 +8,43 @@ import (
...
+func filterUncontrolledResources(resourcesList v1.ResourceList, controlledResoures []string) v1.ResourceList {
 	fillteredList := v1.ResourceList{}
 	for resourceName, quantity := range resourcesList {
 		if slices.Contains(controlledResoures, resourceName.String()) {
-			AddResourcesToList(&fillteredList, quantity, resourceName.String())
+			addResourcesToList(&fillteredList, quantity, resourceName.String())
 		}
 	}
 	return fillteredList
 }
```
Comment (mzeevi) [inline internal/utils/resources.go:22]: Typo in ` fiterUncontrolledResources` and in `fillteredList`

**Comment by mzeevi** [comment]
Added a few comments. Overall this looks good. Remove boilerplate code such as: 

```
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
```

**Comment by mzeevi** [comment]
Also, please add to the `README.md` all the possible hierarchies that this code can work with, since in reality we have different hierarchies and this doesn't fit everything. Also add a link to the HNS git repo in the `README.md`

File: internal/utils/nodeGroup.go [hunk 21]
```diff
@@ -23,90 +29,178 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
+		return err
+	}
+	rootRQ.Spec.Hard = rootResources
+	logger.Info(fmt.Sprintf("Updating RootSubnamespace %s with new resources", rootSubnamespace.RootNamespace))
+	if err := client.Update(ctx, &rootRQ); err != nil {
+		logger.Error(err, fmt.Sprintf("Error updating rootSubnamespace %s", rootSubnamespace.RootNamespace))
+		return err
+	}
+	return nil
+}
```
Comment (mzeevi) [inline internal/utils/nodeGroup.go:120]: The update here is problematic since it overrides quota values which are not controlled by the `NodeQuotaConfig` and can cause the update of the secondary roots to later fail

File: internal/utils/nodeGroup.go (hunk 19 above)
Comment (sahar2339) [reply internal/utils/nodeGroup.go:156]: I am doing this so the `timestamp` won't get overridden with `metav1.now()` and will cause endless updates

File: internal/utils/nodeGroup.go [hunk 22]
```diff
@@ -23,90 +29,178 @@ func CalculateNodeGroup(ctx context.Context, nodes v1.NodeList, config danav1alp
...
 	config.Status.ReservedResources = newReservedResources
 }
 
-func CalculateSecondaryRootPlusDebt(ctx context.Context, r client.Client, sns danav1.Subnamespace, nodegroup danav1alpha1.NodeGroup, config *danav1alpha1.NodeQuotaConfig) (error, v1.ResourceList, v1.ResourceList) {
+// CalculateSecondaryNodeGroup calculates the resource list for a secondary node group based on the provided nodegroup and NodeQuotaConfig.
+// It takes a context, a client for making API requests, a nodegroup to calculate resources for, and the NodeQuotaConfig.
+// It returns an error (if any occurred) and the calculated resource list (v1.ResourceList).
+func CalculateSecondaryNodeGroup(ctx context.Context, r client.Client, nodegroup danav1alpha1.NodeGroup, config *danav1alpha1.NodeQuotaConfig) (error, v1.ResourceList) {
+	logr, _ := logr.FromContext(ctx)
 	labelSelector := labels.SelectorFromSet(labels.Set(nodegroup.LabelSelector))
```
[the remark this answers is not in the document]
Comment (sahar2339) [reply internal/utils/nodeGroup.go:78]: It won't compile without it

**Review by mzeevi — APPROVED** [review]
